# field_06_universal_core.py
# Robotic Assays — Field 6: Universal core methods
# VERSION 2.1 — first module authored natively in the structured-criteria schema
# Builder: Anu Kozhiyalam
#
# WHAT THIS MODULE IS FOR
# -----------------------
# Fields 1, 3, 4 and 5 are organised by industry (biopharma, genomics, HTS,
# core molecular biology). This one is organised by ubiquity: the methods that
# nearly every wet lab runs regardless of what it is trying to make. They were
# the library's largest coverage gap -- the hub could describe PCR *steps*
# (colony PCR, mycoplasma PCR, library enrichment) but had no quantitative qPCR
# assay with a standard curve, which is arguably the most-run quantitative
# measurement in biology.
#
# Every entry here carries BOTH forms of acceptance criteria:
#   acceptance_criteria            -- prose, for a scientist reading the protocol
#   acceptance_criteria_structured -- machine-scorable, see assay_criteria_schema.py
#   well_roles                     -- what a blank/standard/control is held to
#
# A NOTE ON SOURCES, WHICH IS THE POINT OF THIS MODULE
# ----------------------------------------------------
# Every number names its authority and what KIND of authority that is. Two
# findings from building this file, both of which the wider field gets wrong:
#
#   * The qPCR efficiency window of 90-110% and R-squared > 0.980 are cited
#     almost everywhere as MIQE requirements. MIQE does not state them. MIQE
#     requires efficiency and r-squared be REPORTED, and separately gives the
#     NTC rule and the dynamic-range guidance encoded below. The 90-110%
#     window is Bio-Rad application guidance -- real, useful, and not
#     regulatory. It is labelled vendor_guidance here.
#
#   * USP <621> defines HOW to calculate resolution, tailing and plate count
#     and requires that system suitability be established. It does not set
#     universal numeric limits -- those belong to each monograph or method.
#     The familiar R >= 2.0 / T <= 2.0 / RSD <= 2.0% defaults are labelled
#     project_defined, with <621> cited for the methodology.
#
# Where a number genuinely has no external source it says project_defined.
# That is not a weakness in the library; it is the difference between a
# reference and a guess dressed as a reference.

UNIVERSAL_CORE_ASSAYS = [

    # =====================================================================
    {
        "assay_id": "UNI_001",
        "name": "Quantitative PCR (qPCR) with standard curve — absolute quantification",
        "field": "Universal core methods",
        "product_types": ["Nucleic acid samples", "Gene expression studies", "Viral/microbial load", "Library quantification", "GMO and food testing"],
        "purpose": "Determine absolute copy number or concentration of a nucleic acid target by amplifying a dilution series of a known standard alongside unknowns and reading each reaction's quantification cycle (Cq) against the resulting curve.",
        "robot_steps": [
            "Thaw standards, samples and 2x master mix on the cooled block at deck position A1 -- log thaw start time; keep master mix shielded from light if probe-based.",
            "Prepare the standard dilution series at position B1: transfer 90 uL nuclease-free water into wells B1:2 through B1:7, then serially transfer 10 uL from the stock into each in turn, mixing 8 times per step with fresh tips -- yields six 10-fold points spanning 5 log10.",
            "Dispense 15 uL of 2x master mix (primers/probe pre-added) from the reservoir at position C1 into every well of the optical plate at position D1 using 50 uL tips from position E1.",
            "Transfer 5 uL of each standard dilution into its assigned triplicate wells on the optical plate -- lowest concentration first, changing tips between every transfer to prevent carryover up the curve.",
            "Transfer 5 uL of each unknown sample into its assigned triplicate wells.",
            "Transfer 5 uL nuclease-free water into the no-template control (NTC) wells LAST, from a dedicated reservoir at position C2 that no template has contacted.",
            "Seal the optical plate with optically clear film at position F1 -- apply even pressure across all edges; a partial seal evaporates edge wells during cycling.",
            "Centrifuge the sealed plate at 1000 x g for 1 minute to collect droplets and remove bubbles -- bubbles scatter the excitation beam and inflate apparent Cq.",
            "Load the plate into the real-time thermocycler at position G1 and start the run: 95 C for 2 min, then 40 cycles of 95 C for 5 s / 60 C for 30 s with plate read at the 60 C step.",
            "Append a melt curve (65-95 C, 0.5 C increments) when the chemistry is SYBR-based -- probe-based runs skip this step.",
            "[ANALYST STEP -- robot pauses and alerts]: Review amplification curves for non-sigmoidal shape, baseline drift, and any NTC amplification before accepting quantification.",
            "Export Cq values, standard curve slope, efficiency and r-squared to the run file; archive raw amplification and melt data.",
        ],
        "robot_deck_layout": {
            "A1": "Cooled sample block -- standards, samples, master mix (4 C)",
            "B1": "Dilution plate -- 96-well, for the standard series",
            "C1": "Reagent reservoir -- 2x master mix with primers/probe",
            "C2": "Dedicated NTC water reservoir -- never contacted by template",
            "D1": "Optical qPCR plate -- 96-well, clear or white per chemistry",
            "E1": "Tip rack -- 50 uL filtered tips",
            "F1": "Plate sealer -- optically clear film",
            "G1": "Real-time thermocycler interface position",
        },
        "workbench_id": "WB2",
        "rail_handoff": "Plate handed to thermocycler nest; robot releases until cycle complete signal.",
        "instruments_needed": ["Real-time thermocycler with optical detection", "Plate sealer", "Plate centrifuge", "Cooled reagent block"],
        "consumables": ["Optical 96-well qPCR plates", "Optically clear sealing film", "50 uL filtered pipette tips", "Nuclease-free 1.5 mL tubes"],
        "reagents": ["2x qPCR master mix (SYBR or probe-based)", "Forward and reverse primers (validated pair)", "Hydrolysis probe (probe chemistry only)", "Quantified standard (plasmid, gBlock or certified reference material)", "Nuclease-free water"],
        "throughput_samples_per_run": 24,
        "throughput_notes": "24 unknowns in triplicate plus a 6-point standard curve in triplicate and 3 NTC wells fills one 96-well plate exactly (24x3 + 6x3 + 3 = 93 wells used).",
        "robot_active_minutes": 35,
        "total_assay_duration_hours": 2.5,
        "sample_volume_uL": 5,
        "detection": "Fluorescence, real-time per cycle (FAM/SYBR channel)",
        "regulatory": ["MIQE guidelines (Bustin et al., Clin Chem 2009)", "ISO 20395:2019 (nucleic acid quantification performance)"],
        "automation_difficulty": "moderate",
        "acceptance_criteria": {
            "amplification_efficiency": "90-110%",
            "curve_slope": "-3.6 to -3.1 Cq per log10",
            "standard_curve_r2": "> 0.980",
            "ntc_cq": "No amplification, or Cq >= 40",
            "linear_dynamic_range": ">= 3 orders of magnitude across the curve",
            "technical_replicate_cq_sd": "<= 0.5 Cq across triplicates",
            "melt_curve": "Single peak at expected Tm +/- 1 C (SYBR chemistry only)",
        },
        "acceptance_criteria_structured": [
            {"key": "amplification_efficiency", "criterion_type": "curve_efficiency", "scope": "plate",
             "applies_to": "standard", "min": 90.0, "max": 110.0, "unit": "%",
             "display": "90-110%",
             "source": "Bio-Rad Bulletin 5859, 'A Practical Approach to RT-qPCR' -- stated as the practical goal for reaction efficiency",
             "source_type": "vendor_guidance", "machine_scorable": True},
            {"key": "standard_curve_r2", "criterion_type": "curve_r2", "scope": "plate",
             "applies_to": "standard", "min": 0.980, "max": None, "unit": None,
             "display": "> 0.980",
             "source": "Bio-Rad Bulletin 5859 -- 'an r2 value >0.980 is desirable'. NOTE: MIQE requires r2 be reported and sets no threshold; do not cite MIQE for this number",
             "source_type": "vendor_guidance", "machine_scorable": True},
            {"key": "curve_slope", "criterion_type": "curve_slope", "scope": "plate",
             "applies_to": "standard", "min": -3.6, "max": -3.1, "unit": "Cq per log10",
             "display": "-3.6 to -3.1",
             "source": "Arithmetic restatement of the 90-110% efficiency window via E = 10^(-1/slope) - 1",
             "source_type": "vendor_guidance", "machine_scorable": True},
            {"key": "ntc_cq", "criterion_type": "blank_max", "scope": "well",
             "applies_to": "negative_control", "min": 40.0, "max": None, "unit": "Cq",
             "display": "No amplification, or Cq >= 40",
             "source": "MIQE (Bustin 2009): 'NTCs with Cqs >= 40 could be ignored if the Cq for the lowest concentration unknown is <= 35'",
             "source_type": "regulatory", "machine_scorable": True},
            {"key": "linear_dynamic_range", "criterion_type": "linear_range", "scope": "plate",
             "applies_to": "standard", "min": 3.0, "max": None, "unit": "log10 orders",
             "display": ">= 3 orders of magnitude (5-6 preferred)",
             "source": "MIQE (Bustin 2009): dynamic range 'should cover at least 3 orders of magnitude and ideally should extend to 5 or 6 log10 concentrations'",
             "source_type": "regulatory", "machine_scorable": True},
            {"key": "technical_replicate_cq_sd", "criterion_type": "replicate_sd", "scope": "plate",
             "applies_to": "all", "min": None, "max": 0.5, "unit": "Cq",
             "display": "<= 0.5 Cq SD across triplicates",
             "source": "Internal QC SOP (project-defined) -- MIQE requires replicate variation be reported but sets no limit",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "melt_curve", "criterion_type": "contamination_check", "scope": "well",
             "applies_to": "all", "min": None, "max": None, "unit": None,
             "display": "Single peak at expected Tm +/- 1 C (SYBR only)",
             "source": "Standard SYBR specificity check; Tm is target- and buffer-dependent so no universal value exists",
             "source_type": "community_convention", "machine_scorable": False},
        ],
        "well_roles": {
            "sample": {"min": 10.0, "max": 35.0, "unit": "Cq",
                       "note": "An unknown must amplify inside the curve. Above ~35 the measurement sits below reliable quantification; below 10 it is off the top of the curve and needs dilution."},
            "negative_control": {"min": 40.0, "max": None, "unit": "Cq",
                                 "note": "INVERTED RULE. The NTC passes by NOT amplifying: a HIGH Cq (or none) is the good result. The identical Cq of 38 that condemns this well as a sample vindicates it as an NTC."},
            "standard": {"skip": True,
                         "note": "Calibrators are not judged against a range -- they ARE the range. They are scored collectively by the plate-scoped curve criteria above."},
            "positive_control": {"min": 18.0, "max": 28.0, "unit": "Cq",
                                 "note": "Known-input control; a drift outside this window points at master mix or instrument optics before it points at the samples."},
        },
        "environment_requirement": "Standard lab bench (BSL-1); pre- and post-amplification areas should be physically separated to control amplicon contamination.",
        "platform_compatibility": "Full -- but NTC reagents must be staged on a deck position that template tips never cross.",
        "notes": "The single most common cause of a failed qPCR run is contamination of the NTC, not a bad curve. Dispense template low-to-high and load NTC wells last from a dedicated reservoir. If efficiency exceeds 110% suspect inhibitors in the sample rather than celebrating: inhibitors compress the low-concentration end of the curve and steepen the slope. If efficiency falls below 90% check primer design and master mix age before re-running. Freeze-thaw cycles on the quantified standard degrade it; aliquot single-use volumes at first receipt.",
        "autonomy_level": 2,
        "autonomy_level_reason": "Robot performs dilution, dispensing, sealing and loading unattended; analyst reviews curve shape and NTC status before results are accepted.",
        "automate_96_steps": ["Master mix dispense to all 96 wells", "Standard series serial dilution"],
        "automate_96_head": "96-channel head",
        "automate_96_head_note": "Full-plate master mix dispense is a single 96-head aspirate-dispense; template addition stays on the 8-channel or single-channel head because sources differ per well.",
        "automate_96_head_change": True,
        "instrument_assignment": {
            "rail_robot": ["A1", "D1", "F1", "G1"],
            "automate_96": ["B1", "C1", "C2", "E1"],
            "analyst": [],
        },
        "protocol_steps_v3": [
            {"step_number": 1, "step_type": "thaw", "instrument": "cooled_block", "description": "Thaw standards, samples and master mix at 4 C.", "parameters": {"temperature_C": 4}, "duration_seconds": 900},
            {"step_number": 2, "step_type": "serial_dilution", "instrument": "liquid_handler", "description": "Build six 10-fold standard dilutions, mixing 8x per step with fresh tips.", "parameters": {"volume_uL": 10.0, "diluent_uL": 90.0, "points": 6, "fold": 10, "mix_cycles": 8}, "duration_seconds": 420},
            {"step_number": 3, "step_type": "dispense", "instrument": "liquid_handler", "description": "Dispense 15 uL 2x master mix into all 96 wells.", "parameters": {"volume_uL": 15.0, "wells": 96}, "duration_seconds": 180},
            {"step_number": 4, "step_type": "transfer", "instrument": "liquid_handler", "description": "Add 5 uL of each standard dilution in triplicate, lowest concentration first.", "parameters": {"volume_uL": 5.0, "replicates": 3, "order": "low_to_high"}, "duration_seconds": 300},
            {"step_number": 5, "step_type": "transfer", "instrument": "liquid_handler", "description": "Add 5 uL of each unknown sample in triplicate.", "parameters": {"volume_uL": 5.0, "replicates": 3}, "duration_seconds": 480},
            {"step_number": 6, "step_type": "transfer", "instrument": "liquid_handler", "description": "Add 5 uL nuclease-free water to NTC wells last from a dedicated reservoir.", "parameters": {"volume_uL": 5.0, "replicates": 3, "source": "dedicated_ntc_reservoir"}, "duration_seconds": 60},
            {"step_number": 7, "step_type": "seal", "instrument": "plate_sealer", "description": "Seal with optically clear film.", "parameters": {"seal_type": "optical_film"}, "duration_seconds": 45},
            {"step_number": 8, "step_type": "centrifuge", "instrument": "plate_centrifuge", "description": "Spin 1000 x g for 1 minute to collect droplets and clear bubbles.", "parameters": {"rcf": 1000, "duration_seconds": 60}, "duration_seconds": 60},
            {"step_number": 9, "step_type": "thermocycle", "instrument": "real_time_thermocycler", "description": "95 C 2 min; 40 x (95 C 5 s / 60 C 30 s, read at 60 C).", "parameters": {"initial_denature_C": 95, "initial_denature_s": 120, "cycles": 40, "denature_C": 95, "denature_s": 5, "anneal_extend_C": 60, "anneal_extend_s": 30, "read_at": "anneal_extend"}, "duration_seconds": 4200},
            {"step_number": 10, "step_type": "melt_curve", "instrument": "real_time_thermocycler", "description": "Melt 65-95 C in 0.5 C increments (SYBR chemistry only).", "parameters": {"start_C": 65, "end_C": 95, "increment_C": 0.5}, "duration_seconds": 600},
            {"step_number": 11, "step_type": "analyst_review", "instrument": "analyst", "description": "Review curve shape, baseline and NTC status before accepting quantification.", "parameters": {}, "duration_seconds": 600},
            {"step_number": 12, "step_type": "export", "instrument": "real_time_thermocycler", "description": "Export Cq, slope, efficiency and r-squared to the run file.", "parameters": {}, "duration_seconds": 60},
        ],
    },

    # =====================================================================
    {
        "assay_id": "UNI_002",
        "name": "Nucleic acid quantification and purity by UV absorbance (NanoDrop, A260/A280/A230)",
        "field": "Universal core methods",
        "product_types": ["Genomic DNA", "Plasmid DNA", "Total RNA", "PCR products", "Sequencing libraries (screening only)"],
        "purpose": "Measure nucleic acid concentration from absorbance at 260 nm and assess contamination from protein, phenol, guanidine and carbohydrate using the A260/A280 and A260/A230 ratios.",
        "robot_steps": [
            "Equilibrate samples to room temperature at deck position A1 and mix each by pipetting 5 times -- cold or unmixed samples read low and inconsistently.",
            "Blank the instrument with the SAME buffer the samples are dissolved in, loaded from position C1 -- blanking against water when samples are in TE shifts the A230 reading and corrupts the 260/230 ratio.",
            "Verify the blank reads below 0.02 AU at 260 nm; if not, clean the measurement surface and re-blank before proceeding.",
            "Transfer 2 uL of each sample from position A1 to the microvolume measurement pedestal at position D1 using 10 uL tips from position E1.",
            "Read absorbance at 230, 260 and 280 nm; record the full spectrum from 220-350 nm for each sample.",
            "Wipe the pedestal between every sample with a lint-free wipe -- carryover from a concentrated sample inflates the next reading.",
            "Read a buffer blank every 12 samples as a drift check and log the value.",
            "Calculate concentration using the appropriate extinction factor: 50 ng-cm/uL for dsDNA, 40 for RNA, 33 for ssDNA.",
            "Calculate A260/A280 and A260/A230 ratios for every sample and flag those outside the expected window for the nucleic acid type.",
            "Flag any sample whose A260 exceeds the instrument's linear range for dilution and re-read.",
            "Export concentration, both ratios and the full spectrum to the run file.",
        ],
        "robot_deck_layout": {
            "A1": "Sample rack -- 1.5 mL tubes or 96-well plate, room temperature",
            "C1": "Blanking buffer reservoir -- the sample's own elution buffer",
            "D1": "Microvolume spectrophotometer pedestal",
            "E1": "Tip rack -- 10 uL filtered tips",
            "F1": "Lint-free wipe dispenser",
        },
        "workbench_id": "WB1",
        "rail_handoff": None,
        "instruments_needed": ["Microvolume UV-Vis spectrophotometer (NanoDrop-class) or plate reader with UV-transparent microplate"],
        "consumables": ["10 uL filtered pipette tips", "Lint-free wipes", "UV-transparent microplate (plate-reader variant only)"],
        "reagents": ["Elution buffer matching the sample matrix (TE, EB or nuclease-free water)"],
        "throughput_samples_per_run": 48,
        "throughput_notes": "48 samples per run at roughly 20 seconds each including the wipe step; the plate-reader variant reads 96 at once but needs 2 uL in a UV-transparent plate and gives a shorter path length.",
        "robot_active_minutes": 25,
        "total_assay_duration_hours": 0.5,
        "sample_volume_uL": 2,
        "detection": "UV absorbance, 220-350 nm spectrum",
        "regulatory": ["Thermo Fisher TN52646 (nucleic acid purity assessment)", "ISO 20395:2019 (nucleic acid quantification performance)"],
        "automation_difficulty": "easy",
        "acceptance_criteria": {
            "blank_a260_max": "< 0.02 AU",
            "a260_a280_dna": "1.7-2.0 (pure dsDNA reads ~1.8)",
            "a260_a280_rna": "1.9-2.1 (pure RNA reads ~2.0)",
            "a260_a230": "2.0-2.2",
            "a260_linear_range": "0.02-1.5 AU before dilution required",
            "drift_check_blank": "Every 12 samples, < 0.02 AU",
        },
        "acceptance_criteria_structured": [
            {"key": "blank_a260_max", "criterion_type": "blank_max", "scope": "well",
             "applies_to": "blank", "min": None, "max": 0.02, "unit": "AU",
             "display": "< 0.02 AU at 260 nm",
             "source": "Internal QC SOP (project-defined) -- a practical cleanliness floor for a microvolume pedestal",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "a260_a280_dna", "criterion_type": "purity_ratio", "scope": "well",
             "applies_to": "sample", "min": 1.7, "max": 2.0, "unit": "ratio",
             "display": "1.7-2.0 (pure dsDNA ~1.8)",
             "source": "Thermo Fisher TN52646: 'A ratio of ~1.8 is generally accepted as pure for DNA'; the +/-0.1 working window is project-defined",
             "source_type": "vendor_guidance", "machine_scorable": True},
            {"key": "a260_a280_rna", "criterion_type": "purity_ratio", "scope": "well",
             "applies_to": "sample", "min": 1.9, "max": 2.1, "unit": "ratio",
             "display": "1.9-2.1 (pure RNA ~2.0)",
             "source": "Thermo Fisher TN52646: 'a ratio of ~2.0 is generally accepted as pure for RNA'; the +/-0.1 working window is project-defined",
             "source_type": "vendor_guidance", "machine_scorable": True},
            {"key": "a260_a230", "criterion_type": "purity_ratio", "scope": "well",
             "applies_to": "sample", "min": 2.0, "max": 2.2, "unit": "ratio",
             "display": "2.0-2.2",
             "source": "Thermo Fisher TN52646: 'Expected 260/230 values are commonly in the range of 2.0-2.2'",
             "source_type": "vendor_guidance", "machine_scorable": True},
            {"key": "a260_linear_range", "criterion_type": "concentration_range", "scope": "well",
             "applies_to": "sample", "min": 0.02, "max": 1.5, "unit": "AU",
             "display": "0.02-1.5 AU (dilute above, concentrate below)",
             "source": "Bounded by detector linearity at the microvolume path length",
             "source_type": "instrument_physics", "machine_scorable": True},
            {"key": "drift_check_blank", "criterion_type": "blank_max", "scope": "run",
             "applies_to": "blank", "min": None, "max": 0.02, "unit": "AU",
             "display": "Interstitial blank every 12 samples, < 0.02 AU",
             "source": "Internal QC SOP (project-defined) carryover control",
             "source_type": "project_defined", "machine_scorable": True},
        ],
        "well_roles": {
            "sample": {"min": 0.02, "max": 1.5, "unit": "AU",
                       "note": "A260 must sit inside detector linearity. Below 0.02 the reading is noise; above 1.5 it saturates and under-reports."},
            "blank": {"min": None, "max": 0.02, "unit": "AU",
                      "note": "INVERTED RULE. The blank passes by reading as close to zero as possible -- the same 0.015 AU that would be a failed sample is a perfect blank."},
        },
        "environment_requirement": "Standard lab bench (BSL-1)",
        "platform_compatibility": "Full",
        "notes": "The A260/A230 ratio is the one people ignore and the one that predicts downstream failure. A low 260/230 with a perfect 260/280 almost always means residual guanidine or carbohydrate from the extraction column, which passes UV QC and then inhibits ligation, PCR and reverse transcription. Blank with the sample's own buffer, not water: TE absorbs at 230 nm and blanking against water will manufacture a failing ratio out of a clean sample. A high 260/230 (above ~2.4) usually means a dirty pedestal or a mismatched blank rather than an unusually pure sample. Note that absorbance cannot distinguish intact nucleic acid from free nucleotides or degraded fragments -- use fluorometric quantification for library input and a fragment analyser for integrity.",
        "autonomy_level": 1,
        "autonomy_level_reason": "Fully instrument-driven read with no decision points; analyst reviews flagged ratios afterwards.",
        "automate_96_steps": [],
        "automate_96_head": "not applicable",
        "automate_96_head_note": "Microvolume pedestal reads one sample at a time; no microplate dispensing in the standard variant.",
        "automate_96_head_change": False,
        "instrument_assignment": {
            "rail_robot": ["A1", "D1", "F1"],
            "automate_96": ["C1", "E1"],
            "analyst": [],
        },
        "protocol_steps_v3": [
            {"step_number": 1, "step_type": "equilibrate", "instrument": "liquid_handler", "description": "Bring samples to room temperature and mix 5x.", "parameters": {"mix_cycles": 5}, "duration_seconds": 300},
            {"step_number": 2, "step_type": "blank", "instrument": "spectrophotometer", "description": "Blank with the sample's own elution buffer.", "parameters": {"wavelengths_nm": [230, 260, 280]}, "duration_seconds": 60},
            {"step_number": 3, "step_type": "verify", "instrument": "spectrophotometer", "description": "Confirm blank reads < 0.02 AU at 260 nm.", "parameters": {"max_AU": 0.02}, "duration_seconds": 20},
            {"step_number": 4, "step_type": "transfer", "instrument": "liquid_handler", "description": "Load 2 uL of sample onto the pedestal.", "parameters": {"volume_uL": 2.0}, "duration_seconds": 15},
            {"step_number": 5, "step_type": "read", "instrument": "spectrophotometer", "description": "Read full spectrum 220-350 nm.", "parameters": {"start_nm": 220, "end_nm": 350}, "duration_seconds": 10},
            {"step_number": 6, "step_type": "clean", "instrument": "liquid_handler", "description": "Wipe pedestal with a lint-free wipe between samples.", "parameters": {}, "duration_seconds": 10},
            {"step_number": 7, "step_type": "qc_check", "instrument": "spectrophotometer", "description": "Interstitial buffer blank every 12 samples.", "parameters": {"interval_samples": 12, "max_AU": 0.02}, "duration_seconds": 30},
            {"step_number": 8, "step_type": "calculate", "instrument": "software", "description": "Apply extinction factor by nucleic acid type and compute both purity ratios.", "parameters": {"dsDNA_factor": 50, "RNA_factor": 40, "ssDNA_factor": 33}, "duration_seconds": 15},
            {"step_number": 9, "step_type": "export", "instrument": "software", "description": "Export concentration, ratios and spectra.", "parameters": {}, "duration_seconds": 30},
        ],
    },

    # =====================================================================
    {
        "assay_id": "UNI_003",
        "name": "Total protein quantification by Bradford assay (96-well microplate)",
        "field": "Universal core methods",
        "product_types": ["Cell lysates", "Purified protein", "Column fractions", "Culture supernatant", "Tissue homogenates"],
        "purpose": "Determine total protein concentration by Coomassie dye binding, reading absorbance at 595 nm against a BSA standard curve prepared on the same plate.",
        "robot_steps": [
            "Equilibrate Bradford reagent to room temperature at deck position C1 -- cold reagent gives a suppressed and drifting signal; log the equilibration start time.",
            "Prepare the BSA standard series at position B1: eight points from 1500 down to 0 ug/mL by serial dilution in the sample's own buffer, mixing 6 times per step.",
            "Dispense 5 uL of each standard into its assigned triplicate wells on the 96-well flat-bottom plate at position D1 using 20 uL tips from position E1.",
            "Dispense 5 uL of each unknown sample into its assigned triplicate wells.",
            "Dispense 5 uL of sample buffer alone into the blank wells -- the blank must be the buffer, not water, because detergent and reducing agent both shift the dye.",
            "Add 250 uL Bradford reagent to every well from the reservoir at position C1 using the 96-channel head -- dispense down the well wall, not into the liquid, to avoid splashing between wells.",
            "Mix on the plate shaker at position F1 for 30 seconds at 500 rpm.",
            "Incubate at room temperature for 10 minutes, shielded from direct light.",
            "Read absorbance at 595 nm on the plate reader at position G1 within 60 minutes of reagent addition -- the dye-protein complex drifts after that.",
            "Subtract the mean blank absorbance from every well before fitting.",
            "Fit the standard curve; a four-parameter or quadratic fit is expected to outperform a linear fit across the full range.",
            "Flag any sample whose blank-corrected absorbance falls outside the highest and lowest standards for dilution and re-read.",
            "Export per-well absorbance, fitted concentrations and curve statistics to the run file.",
        ],
        "robot_deck_layout": {
            "A1": "Sample rack -- lysates and fractions, on ice",
            "B1": "Standard dilution plate -- BSA series",
            "C1": "Reagent reservoir -- Bradford (Coomassie) reagent, room temperature",
            "D1": "Assay plate -- 96-well flat-bottom, clear",
            "E1": "Tip rack -- 20 uL filtered tips",
            "E2": "Tip rack -- 300 uL tips for reagent addition",
            "F1": "Plate shaker",
            "G1": "Absorbance plate reader",
        },
        "workbench_id": "WB1",
        "rail_handoff": None,
        "instruments_needed": ["Absorbance plate reader (595 nm)", "Plate shaker", "Cooled sample block"],
        "consumables": ["96-well flat-bottom clear plates", "20 uL and 300 uL filtered tips", "Reagent reservoirs"],
        "reagents": ["Bradford (Coomassie) reagent", "BSA standard, 2 mg/mL", "Sample buffer for blanks and dilutions"],
        "throughput_samples_per_run": 24,
        "throughput_notes": "24 unknowns in triplicate plus an 8-point BSA curve in triplicate fills 96 wells exactly; a second plate doubles throughput with one shared curve only if both plates are read within the 60-minute window.",
        "robot_active_minutes": 20,
        "total_assay_duration_hours": 0.75,
        "sample_volume_uL": 5,
        "detection": "Absorbance 595 nm",
        "regulatory": ["USP <1057> (biotechnology-derived articles -- total protein assay)", "ICH Q6B", "Thermo Fisher Pierce Bradford Plus kit insert MAN0011203"],
        "automation_difficulty": "easy",
        "acceptance_criteria": {
            "standard_curve_r2": ">= 0.980",
            "curve_fit_model": "Four-parameter or quadratic fit, not purely linear",
            "blank_a595_max": "<= 0.10 AU after buffer-only wells",
            "working_range_standard": "100-1500 ug/mL (standard microplate protocol)",
            "working_range_micro": "1-25 ug/mL (micro microplate protocol)",
            "triplicate_cv_max": "<= 10% CV across sample triplicates",
            "bsa_midpoint_recovery": "90-110% of nominal for the mid-curve standard back-calculated against the fit",
            "read_window": "Within 60 minutes of reagent addition",
        },
        "acceptance_criteria_structured": [
            {"key": "standard_curve_r2", "criterion_type": "curve_r2", "scope": "plate",
             "applies_to": "standard", "min": 0.980, "max": None, "unit": None,
             "display": ">= 0.980",
             "source": "Internal QC SOP (project-defined); the kit insert specifies fit MODEL but no r-squared threshold",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "curve_fit_model", "criterion_type": "curve_fit_model", "scope": "plate",
             "applies_to": "standard", "min": None, "max": None, "unit": None,
             "display": "Four-parameter or quadratic fit, not purely linear",
             "source": "Pierce Bradford Plus insert MAN0011203: 'a four-parameter (quadratic) or best-fit curve will provide more accurate results than a purely linear fit'",
             "source_type": "vendor_guidance", "machine_scorable": False},
            {"key": "blank_a595_max", "criterion_type": "blank_max", "scope": "well",
             "applies_to": "blank", "min": None, "max": 0.10, "unit": "AU",
             "display": "<= 0.10 AU",
             "source": "Internal QC SOP (project-defined); consistent with the blank_od562_max used for BCA in BIO_002",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "working_range_standard", "criterion_type": "concentration_range", "scope": "well",
             "applies_to": "sample", "min": 100.0, "max": 1500.0, "unit": "ug/mL",
             "display": "100-1500 ug/mL",
             "source": "Pierce Bradford Plus insert MAN0011203, standard microplate protocol working range",
             "source_type": "vendor_guidance", "machine_scorable": True},
            {"key": "working_range_micro", "criterion_type": "concentration_range", "scope": "well",
             "applies_to": "sample", "min": 1.0, "max": 25.0, "unit": "ug/mL",
             "display": "1-25 ug/mL (micro protocol)",
             "source": "Pierce Bradford Plus insert MAN0011203, micro microplate protocol working range",
             "source_type": "vendor_guidance", "machine_scorable": True},
            {"key": "triplicate_cv_max", "criterion_type": "replicate_cv", "scope": "plate",
             "applies_to": "sample", "min": None, "max": 10.0, "unit": "%",
             "display": "<= 10% CV",
             "source": "Internal QC SOP (project-defined)",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "bsa_midpoint_recovery", "criterion_type": "recovery", "scope": "plate",
             "applies_to": "standard", "min": 90.0, "max": 110.0, "unit": "%",
             "display": "90-110% of nominal",
             "source": "Internal QC SOP (project-defined) back-calculation check on the fit",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "read_window", "criterion_type": "other", "scope": "run",
             "applies_to": "all", "min": None, "max": 60.0, "unit": "minutes",
             "display": "Read within 60 minutes of reagent addition",
             "source": "Pierce Bradford Plus insert MAN0011203 -- 10 minute incubation, complex drifts thereafter",
             "source_type": "vendor_guidance", "machine_scorable": True},
        ],
        "well_roles": {
            "sample": {"min": 0.10, "max": 2.0, "unit": "AU",
                       "note": "Blank-corrected A595. Below the lowest standard the fit extrapolates; above the highest it saturates."},
            "blank": {"min": None, "max": 0.10, "unit": "AU",
                      "note": "INVERTED RULE. Buffer-only wells pass by staying low. Blank with the sample buffer, not water -- detergent and reducing agent shift the dye."},
            "standard": {"skip": True,
                         "note": "BSA calibrators define the curve and are scored by the plate-scoped fit criteria, not by a per-well range."},
        },
        "environment_requirement": "Standard lab bench (BSL-1)",
        "platform_compatibility": "Full",
        "notes": "Bradford is fast and detergent-intolerant; BCA is slower and reducing-agent-intolerant. Choose by what is in the buffer, not by habit. Coomassie binds arginine and aromatic residues preferentially, so protein-to-protein response varies by up to twofold -- a BSA-calibrated result on a lysate is a relative number, and comparing across preparations with different composition is the most common misuse of this assay. Where absolute accuracy matters, calibrate against the protein of interest rather than BSA. The dye binds to plastic: use the same plate lot across a study and never reuse plates.",
        "autonomy_level": 2,
        "autonomy_level_reason": "Robot runs dilution, dispensing, mixing and reading unattended; analyst reviews curve fit and out-of-range flags.",
        "automate_96_steps": ["Bradford reagent addition to all 96 wells", "BSA standard serial dilution"],
        "automate_96_head": "96-channel head",
        "automate_96_head_note": "Reagent addition is a single 96-head dispense; sample and standard transfers use the 8-channel head because sources differ per well.",
        "automate_96_head_change": True,
        "instrument_assignment": {
            "rail_robot": ["A1", "D1", "F1", "G1"],
            "automate_96": ["B1", "C1", "E1", "E2"],
            "analyst": [],
        },
        "protocol_steps_v3": [
            {"step_number": 1, "step_type": "equilibrate", "instrument": "liquid_handler", "description": "Bring Bradford reagent to room temperature.", "parameters": {"temperature_C": 22}, "duration_seconds": 1800},
            {"step_number": 2, "step_type": "serial_dilution", "instrument": "liquid_handler", "description": "Build an 8-point BSA series, 1500 to 0 ug/mL.", "parameters": {"points": 8, "top_ug_per_mL": 1500, "mix_cycles": 6}, "duration_seconds": 360},
            {"step_number": 3, "step_type": "transfer", "instrument": "liquid_handler", "description": "Dispense 5 uL standards in triplicate.", "parameters": {"volume_uL": 5.0, "replicates": 3}, "duration_seconds": 240},
            {"step_number": 4, "step_type": "transfer", "instrument": "liquid_handler", "description": "Dispense 5 uL unknowns in triplicate.", "parameters": {"volume_uL": 5.0, "replicates": 3}, "duration_seconds": 360},
            {"step_number": 5, "step_type": "transfer", "instrument": "liquid_handler", "description": "Dispense 5 uL sample buffer into blank wells.", "parameters": {"volume_uL": 5.0, "replicates": 3}, "duration_seconds": 45},
            {"step_number": 6, "step_type": "dispense", "instrument": "liquid_handler", "description": "Add 250 uL Bradford reagent to all wells down the wall.", "parameters": {"volume_uL": 250.0, "wells": 96, "dispense_mode": "wall"}, "duration_seconds": 120},
            {"step_number": 7, "step_type": "mix", "instrument": "plate_shaker", "description": "Shake 30 s at 500 rpm.", "parameters": {"rpm": 500, "duration_seconds": 30}, "duration_seconds": 30},
            {"step_number": 8, "step_type": "incubate", "instrument": "plate_shaker", "description": "Incubate 10 minutes at room temperature, shielded from light.", "parameters": {"temperature_C": 22, "duration_seconds": 600}, "duration_seconds": 600},
            {"step_number": 9, "step_type": "read", "instrument": "plate_reader", "description": "Read absorbance at 595 nm.", "parameters": {"wavelength_nm": 595}, "duration_seconds": 60},
            {"step_number": 10, "step_type": "calculate", "instrument": "software", "description": "Blank-subtract, fit 4PL/quadratic curve, back-calculate unknowns.", "parameters": {"fit": "4PL_or_quadratic"}, "duration_seconds": 30},
            {"step_number": 11, "step_type": "export", "instrument": "software", "description": "Export per-well absorbance, concentrations and curve statistics.", "parameters": {}, "duration_seconds": 30},
        ],
    },

    # =====================================================================
    {
        "assay_id": "UNI_004",
        "name": "Microbial growth kinetics by OD600 (96-well plate reader)",
        "field": "Universal core methods",
        "product_types": ["Bacterial strains", "Yeast strains", "Strain engineering screens", "Antibiotic and inhibitor testing", "Media and carbon-source development"],
        "purpose": "Track optical density at 600 nm over time for many culture conditions in parallel to derive lag time, maximum specific growth rate and final biomass, and to compare strains, media or inhibitor concentrations quantitatively.",
        "robot_steps": [
            "Prepare the media plate at deck position D1: dispense 198 uL of each test medium from the reservoir bank at position C1 into its assigned wells using the 96-channel head.",
            "Reserve at least three wells per medium as media-only blanks -- these receive no inoculum and carry the sterility and background-absorbance check for that medium.",
            "Fill the entire outer perimeter of the plate with 200 uL sterile water or PBS from position C2 -- edge wells evaporate faster than interior wells and their growth curves are not comparable.",
            "Measure the OD600 of each overnight culture at position A1 and calculate the volume needed to reach a starting OD600 of 0.05 in 200 uL.",
            "Inoculate 2 uL of normalised overnight culture into each assigned sample well, mixing 5 times with fresh tips per well.",
            "Read the plate immediately at position G1 to establish the t=0 baseline and confirm starting OD is within tolerance across all sample wells.",
            "Seal the plate with a gas-permeable membrane from position F1 -- an airtight seal starves aerobic cultures and flattens the curve.",
            "Start the kinetic run: 37 C with continuous orbital shaking at 200 rpm, reading OD600 every 15 minutes for 18 hours.",
            "Robot monitors the media-only blank wells at each read; flag the run immediately if any blank rises more than 0.05 above its t=0 value (contamination).",
            "[ANALYST STEP -- robot pauses and alerts if triggered]: Review any contamination flag and decide whether to abort the run before further incubation.",
            "On completion, subtract the mean media-only blank per medium from every sample well at every timepoint.",
            "Fit the log-linear phase of each blank-corrected curve to derive maximum specific growth rate and doubling time; log the fit r-squared per well.",
            "Export the full time series, per-well growth parameters and fit statistics to the run file.",
        ],
        "robot_deck_layout": {
            "A1": "Overnight culture rack -- source cultures for normalisation",
            "C1": "Reagent reservoir bank -- test media",
            "C2": "Reagent reservoir -- sterile water or PBS for the perimeter moat",
            "D1": "Assay plate -- 96-well flat-bottom, clear, sterile",
            "E1": "Tip rack -- 20 uL sterile filtered tips",
            "E2": "Tip rack -- 300 uL sterile tips for media dispensing",
            "F1": "Gas-permeable membrane sealer",
            "G1": "Kinetic plate reader with temperature control and shaking",
        },
        "workbench_id": "WB3",
        "rail_handoff": "Plate handed to the reader nest and held for the full 18-hour kinetic run; robot released for other work.",
        "instruments_needed": ["Plate reader with 600 nm absorbance, temperature control to 37 C and orbital shaking", "Biosafety cabinet or clean enclosure for inoculation"],
        "consumables": ["96-well flat-bottom sterile clear plates", "Gas-permeable sealing membranes", "Sterile filtered tips, 20 uL and 300 uL"],
        "reagents": ["Test media (LB, M9, defined minimal or experimental formulations)", "Sterile water or PBS for the perimeter moat", "Overnight cultures of the test strains"],
        "throughput_samples_per_run": 60,
        "throughput_notes": "60 test wells per plate after reserving the 36-well perimeter moat and at least 3 media-only blanks per medium; an 18-hour run is unattended, so throughput is set by plate count and reader capacity rather than by hands-on time.",
        "robot_active_minutes": 30,
        "total_assay_duration_hours": 18.5,
        "sample_volume_uL": 2,
        "detection": "Absorbance 600 nm, kinetic (every 15 minutes)",
        "regulatory": ["Internal QC SOP (project-defined)"],
        "automation_difficulty": "easy",
        "acceptance_criteria": {
            "media_blank_od600_max": "<= 0.05 above t=0 across the full run (sterility)",
            "starting_od600": "0.05 +/- 0.01 across all sample wells",
            "growth_rate_fit_r2": ">= 0.980 over the log-linear phase",
            "replicate_cv_max": "<= 15% CV on maximum specific growth rate across replicate wells",
            "positive_control_doubling_time": "20-30 minutes for E. coli in LB at 37 C",
            "edge_well_exclusion": "Perimeter wells filled with moat, excluded from analysis",
        },
        "acceptance_criteria_structured": [
            {"key": "media_blank_od600_max", "criterion_type": "blank_max", "scope": "well",
             "applies_to": "blank", "min": None, "max": 0.05, "unit": "OD600",
             "display": "<= 0.05 rise above t=0",
             "source": "Internal QC SOP (project-defined) sterility check",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "starting_od600", "criterion_type": "control_response", "scope": "well",
             "applies_to": "sample", "min": 0.04, "max": 0.06, "unit": "OD600",
             "display": "0.05 +/- 0.01 at t=0",
             "source": "Internal QC SOP (project-defined) -- comparable curves require a common starting biomass",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "growth_rate_fit_r2", "criterion_type": "curve_r2", "scope": "plate",
             "applies_to": "sample", "min": 0.980, "max": None, "unit": None,
             "display": ">= 0.980 over the log-linear phase",
             "source": "Internal QC SOP (project-defined)",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "replicate_cv_max", "criterion_type": "replicate_cv", "scope": "plate",
             "applies_to": "sample", "min": None, "max": 15.0, "unit": "%",
             "display": "<= 15% CV on growth rate",
             "source": "Internal QC SOP (project-defined) -- biological replicates carry more spread than analytical ones",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "positive_control_doubling_time", "criterion_type": "control_response", "scope": "plate",
             "applies_to": "positive_control", "min": 20.0, "max": 30.0, "unit": "minutes",
             "display": "20-30 min (E. coli, LB, 37 C)",
             "source": "Textbook doubling time for E. coli in rich medium at 37 C; strain- and medium-dependent, so treat as a plate-health check rather than a specification",
             "source_type": "community_convention", "machine_scorable": True},
            {"key": "edge_well_exclusion", "criterion_type": "other", "scope": "plate",
             "applies_to": "all", "min": None, "max": None, "unit": None,
             "display": "Perimeter filled with moat and excluded from analysis",
             "source": "Internal QC SOP (project-defined) evaporation control",
             "source_type": "project_defined", "machine_scorable": False},
        ],
        "well_roles": {
            "sample": {"min": 0.04, "max": 2.0, "unit": "OD600",
                       "note": "Starts at 0.05 and must rise. Above ~1.0 the relationship between OD and biomass goes non-linear at standard path length; above 2.0 the reading is saturated."},
            "blank": {"min": None, "max": 0.10, "unit": "OD600",
                      "note": "INVERTED RULE. Media-only wells pass by NOT growing. A rise of more than 0.05 over the run means the medium or the plate was contaminated, which invalidates every sample sharing that medium."},
            "positive_control": {"min": 0.5, "max": 2.0, "unit": "OD600",
                                 "note": "A known strain in a known medium. If the positive control fails to grow, the run failed for a plate-level reason -- reader temperature, seal, or inoculum handling -- and the sample wells say nothing about the strains."},
        },
        "environment_requirement": "BSL-1 for laboratory strains; inoculation performed in a biosafety cabinet or clean enclosure to protect the media-only blanks.",
        "platform_compatibility": "Full -- requires a reader with temperature control and shaking; a reader without shaking gives settled, non-comparable curves for motile and flocculating strains.",
        "notes": "Three failure modes account for most bad growth-curve data and all three are layout problems rather than biology. First, the edge effect: perimeter wells evaporate faster, concentrate the medium and read artefactually high, which is why the perimeter is filled with a moat and excluded rather than used. Second, an airtight seal: aerobic cultures asphyxiate and the curve flattens in a way that mimics a genuine growth defect -- use a gas-permeable membrane. Third, an unmatched blank: each medium needs its own media-only wells, because a rich medium and a defined minimal medium have different background absorbance and subtracting the wrong one shifts every derived rate. OD600 measures light scattering, not viable cells: it counts dead cells, debris and aggregates, so pair it with plating or a viability stain whenever the question is about live biomass rather than turbidity.",
        "autonomy_level": 3,
        "autonomy_level_reason": "18-hour unattended kinetic run with in-run contamination monitoring on the blank wells; the robot raises an alert and pauses only on a triggered flag.",
        "automate_96_steps": ["Media dispense to all wells", "Perimeter moat fill"],
        "automate_96_head": "96-channel head",
        "automate_96_head_note": "Media and moat fills are full-plate 96-head dispenses; inoculation uses the 8-channel head because each well takes a different normalised culture volume.",
        "automate_96_head_change": True,
        "instrument_assignment": {
            "rail_robot": ["A1", "D1", "F1", "G1"],
            "automate_96": ["C1", "C2", "E1", "E2"],
            "analyst": [],
        },
        "protocol_steps_v3": [
            {"step_number": 1, "step_type": "dispense", "instrument": "liquid_handler", "description": "Dispense 198 uL test media into assigned wells.", "parameters": {"volume_uL": 198.0}, "duration_seconds": 150},
            {"step_number": 2, "step_type": "dispense", "instrument": "liquid_handler", "description": "Reserve >= 3 media-only blank wells per medium.", "parameters": {"min_blanks_per_medium": 3}, "duration_seconds": 30},
            {"step_number": 3, "step_type": "dispense", "instrument": "liquid_handler", "description": "Fill perimeter moat with 200 uL sterile water or PBS.", "parameters": {"volume_uL": 200.0, "wells": 36}, "duration_seconds": 90},
            {"step_number": 4, "step_type": "read", "instrument": "plate_reader", "description": "Measure overnight culture OD600 and compute normalisation volumes.", "parameters": {"wavelength_nm": 600, "target_start_OD": 0.05}, "duration_seconds": 120},
            {"step_number": 5, "step_type": "transfer", "instrument": "liquid_handler", "description": "Inoculate 2 uL normalised culture per sample well, mixing 5x.", "parameters": {"volume_uL": 2.0, "mix_cycles": 5}, "duration_seconds": 420},
            {"step_number": 6, "step_type": "read", "instrument": "plate_reader", "description": "t=0 baseline read; confirm starting OD tolerance.", "parameters": {"wavelength_nm": 600}, "duration_seconds": 60},
            {"step_number": 7, "step_type": "seal", "instrument": "plate_sealer", "description": "Apply gas-permeable membrane.", "parameters": {"seal_type": "gas_permeable"}, "duration_seconds": 45},
            {"step_number": 8, "step_type": "kinetic_read", "instrument": "plate_reader", "description": "37 C, 200 rpm orbital, OD600 every 15 min for 18 h.", "parameters": {"temperature_C": 37, "rpm": 200, "interval_seconds": 900, "duration_seconds": 64800, "wavelength_nm": 600}, "duration_seconds": 64800},
            {"step_number": 9, "step_type": "qc_check", "instrument": "software", "description": "Monitor media-only blanks each read; flag any rise > 0.05.", "parameters": {"max_blank_rise_OD": 0.05}, "duration_seconds": 0},
            {"step_number": 10, "step_type": "analyst_review", "instrument": "analyst", "description": "Review any contamination flag and decide whether to abort.", "parameters": {}, "duration_seconds": 300},
            {"step_number": 11, "step_type": "calculate", "instrument": "software", "description": "Blank-subtract per medium, fit log-linear phase, derive growth rate and doubling time.", "parameters": {"fit": "log_linear"}, "duration_seconds": 60},
            {"step_number": 12, "step_type": "export", "instrument": "software", "description": "Export time series, growth parameters and fit statistics.", "parameters": {}, "duration_seconds": 60},
        ],
    },

    # =====================================================================
    {
        "assay_id": "UNI_005",
        "name": "Quantitative LC-MS/MS bioanalysis (regulated, ICH M10)",
        "field": "Universal core methods",
        "product_types": ["Plasma and serum samples", "Tissue homogenates", "Pharmacokinetic studies", "Toxicokinetic studies", "Biomarker quantification"],
        "purpose": "Quantify an analyte in a biological matrix against a matrix-matched calibration curve with a stable-isotope-labelled internal standard, to the acceptance criteria required for regulated bioanalysis.",
        "robot_steps": [
            "Thaw study samples, calibration standards and quality control samples on the cooled block at deck position A1 -- log thaw start; record any sample that has exceeded its permitted freeze-thaw count.",
            "Vortex-mix every thawed sample for 10 seconds and centrifuge at 3000 x g for 5 minutes at 4 C to pellet fibrin and debris.",
            "Dispense 20 uL internal standard working solution from the reservoir at position C1 into every well of the extraction plate at position D1 EXCEPT the double-blank wells.",
            "Transfer 50 uL of each calibration standard, QC sample, study sample and blank into its assigned well using 200 uL tips from position E1, changing tips between every transfer.",
            "Add 150 uL cold acetonitrile from position C2 to precipitate protein -- dispense rapidly against the well wall to maximise mixing at the moment of addition.",
            "Seal, shake at 1000 rpm for 5 minutes at position F1, then centrifuge the extraction plate at 4000 x g for 10 minutes at 4 C.",
            "Transfer 100 uL of supernatant from each well to the clean injection plate at position D2 without disturbing the protein pellet -- aspirate from a fixed height above the pellet, not from the well bottom.",
            "Dilute each transferred supernatant with 100 uL of aqueous mobile phase and mix 5 times.",
            "Seal the injection plate and load it into the autosampler at position G1 held at 8 C.",
            "Inject in the validated run order: system suitability injection, then blanks, then calibration standards low to high, then QCs and study samples interleaved, with a blank immediately following the highest standard to measure carryover.",
            "[ANALYST STEP -- robot pauses and alerts]: Review peak integration, internal standard response consistency and carryover blank before accepting the run.",
            "Export peak areas, analyte-to-internal-standard ratios, back-calculated concentrations and the regression model to the run file.",
        ],
        "robot_deck_layout": {
            "A1": "Cooled sample block -- study samples, calibrators, QCs (4 C)",
            "C1": "Reagent reservoir -- stable-isotope-labelled internal standard working solution",
            "C2": "Reagent reservoir -- cold acetonitrile (protein precipitation)",
            "C3": "Reagent reservoir -- aqueous mobile phase for dilution",
            "D1": "Extraction plate -- 96-well, 2 mL deep well",
            "D2": "Injection plate -- 96-well, shallow, LC-compatible",
            "E1": "Tip rack -- 200 uL filtered tips",
            "F1": "Plate shaker and sealer station",
            "G1": "LC-MS/MS autosampler interface, 8 C",
        },
        "workbench_id": "WB4",
        "rail_handoff": "Injection plate handed to the LC-MS/MS autosampler nest; robot released for the duration of the analytical run.",
        "instruments_needed": ["LC-MS/MS triple quadrupole with autosampler", "Refrigerated plate centrifuge", "Plate shaker", "Plate sealer", "Cooled reagent block"],
        "consumables": ["96-well 2 mL deep-well plates", "96-well shallow LC injection plates", "200 uL filtered tips", "Pierceable sealing mats"],
        "reagents": ["Stable-isotope-labelled internal standard", "LC-MS grade acetonitrile", "LC-MS grade water and modifiers", "Blank matrix from at least 6 individual lots", "Certified analyte reference standard"],
        "throughput_samples_per_run": 60,
        "throughput_notes": "One 96-well plate holds a full validated run: 8 calibration levels, QCs at 4 levels in replicate, blanks and double blanks, and roughly 60 study samples.",
        "robot_active_minutes": 55,
        "total_assay_duration_hours": 6,
        "sample_volume_uL": 50,
        "detection": "Tandem mass spectrometry, multiple reaction monitoring (MRM)",
        "regulatory": ["ICH M10 (Bioanalytical Method Validation and Study Sample Analysis, Step 4, 2022)", "FDA Bioanalytical Method Validation Guidance", "EMA ICH M10 Step 5"],
        "automation_difficulty": "hard",
        "acceptance_criteria": {
            "calibration_standard_accuracy": "Within +/-15% of nominal",
            "calibration_standard_accuracy_lloq": "Within +/-20% of nominal at LLOQ",
            "calibration_levels_minimum": "At least 6 concentration levels",
            "calibration_pass_rate": "At least 75% of calibration standards must meet criteria",
            "qc_accuracy": "Within +/-15% of nominal (+/-20% at LLOQ QC)",
            "qc_precision_cv": "<= 15% CV (<= 20% at LLOQ QC)",
            "qc_replicates": "At least 5 replicates per QC level, at least 3 runs over at least 2 days",
            "carryover_analyte": "<= 20% of the analyte response at LLOQ in a blank following the highest standard",
            "carryover_internal_standard": "<= 5% of the internal standard response",
            "matrix_effect_sources": "At least 6 different matrix sources/lots, accuracy +/-15%, precision <= 15%",
        },
        "acceptance_criteria_structured": [
            {"key": "calibration_standard_accuracy", "criterion_type": "calibration_accuracy", "scope": "plate",
             "applies_to": "standard", "min": 85.0, "max": 115.0, "unit": "% of nominal",
             "display": "Within +/-15% of nominal",
             "source": "ICH M10 Step 4 (2022): calibration standards 'within +/-15% of the nominal concentration'",
             "source_type": "regulatory", "machine_scorable": True},
            {"key": "calibration_standard_accuracy_lloq", "criterion_type": "calibration_accuracy", "scope": "plate",
             "applies_to": "standard", "min": 80.0, "max": 120.0, "unit": "% of nominal",
             "display": "Within +/-20% of nominal at LLOQ",
             "source": "ICH M10 Step 4 (2022): at LLOQ 'within +/-20% of the nominal concentration'",
             "source_type": "regulatory", "machine_scorable": True},
            {"key": "calibration_levels_minimum", "criterion_type": "linear_range", "scope": "plate",
             "applies_to": "standard", "min": 6.0, "max": None, "unit": "levels",
             "display": "At least 6 concentration levels",
             "source": "ICH M10 Step 4 (2022): 'at least 6 concentration levels'",
             "source_type": "regulatory", "machine_scorable": True},
            {"key": "calibration_pass_rate", "criterion_type": "calibration_accuracy", "scope": "plate",
             "applies_to": "standard", "min": 75.0, "max": None, "unit": "%",
             "display": "At least 75% of standards must pass",
             "source": "ICH M10 Step 4 (2022): 'At least 75% of the calibration standards should meet the above criteria'",
             "source_type": "regulatory", "machine_scorable": True},
            {"key": "qc_accuracy", "criterion_type": "recovery", "scope": "plate",
             "applies_to": "qc", "min": 85.0, "max": 115.0, "unit": "% of nominal",
             "display": "Within +/-15% of nominal",
             "source": "ICH M10 Step 4 (2022) QC accuracy criterion",
             "source_type": "regulatory", "machine_scorable": True},
            {"key": "qc_precision_cv", "criterion_type": "replicate_cv", "scope": "plate",
             "applies_to": "qc", "min": None, "max": 15.0, "unit": "%",
             "display": "<= 15% CV (<= 20% at LLOQ QC)",
             "source": "ICH M10 Step 4 (2022): precision '%CV should not exceed 15%'",
             "source_type": "regulatory", "machine_scorable": True},
            {"key": "carryover_analyte", "criterion_type": "carryover", "scope": "run",
             "applies_to": "blank", "min": None, "max": 20.0, "unit": "% of LLOQ response",
             "display": "<= 20% of LLOQ response in the blank after the highest standard",
             "source": "ICH M10 Step 4 (2022): 'Carry-over in the blank samples following the highest calibration standard should not be greater than 20% of the analyte response at the LLOQ'",
             "source_type": "regulatory", "machine_scorable": True},
            {"key": "carryover_internal_standard", "criterion_type": "carryover", "scope": "run",
             "applies_to": "blank", "min": None, "max": 5.0, "unit": "% of IS response",
             "display": "<= 5% of the internal standard response",
             "source": "ICH M10 Step 4 (2022): 'and 5% of the response for the IS'",
             "source_type": "regulatory", "machine_scorable": True},
            {"key": "matrix_effect_sources", "criterion_type": "other", "scope": "run",
             "applies_to": "all", "min": 6.0, "max": None, "unit": "lots",
             "display": "At least 6 different matrix sources/lots",
             "source": "ICH M10 Step 4 (2022): matrix effect evaluated in 'at least 6 different sources/lots'",
             "source_type": "regulatory", "machine_scorable": True},
        ],
        "well_roles": {
            "sample": {"min": None, "max": None, "unit": "ng/mL", "skip": True,
                       "note": "A study sample has no acceptance range -- its concentration is the RESULT. It is judged only by whether it falls inside the validated calibration range; outside it, the sample is diluted and reanalysed rather than reported."},
            "standard": {"skip": True,
                         "note": "Calibrators define the curve and are scored by the plate-scoped accuracy and pass-rate criteria."},
            "qc": {"min": 85.0, "max": 115.0, "unit": "% of nominal",
                   "note": "Known-concentration checks at low, mid and high. The QCs, not the samples, decide whether a run is accepted."},
            "blank": {"min": None, "max": 20.0, "unit": "% of LLOQ response",
                      "note": "INVERTED RULE. A blank passes by showing almost nothing. Placed immediately after the highest standard it measures carryover; the same signal that would be an ordinary low sample is a failing blank."},
            "negative_control": {"min": None, "max": 5.0, "unit": "% of IS response",
                                 "note": "Double blank -- no analyte and no internal standard. Detects interference from the matrix itself and contamination of the IS channel."},
        },
        "environment_requirement": "Standard analytical laboratory; controlled-temperature autosampler at 8 C; regulated studies require controlled access and full chain-of-custody records.",
        "platform_compatibility": "Full for the extraction; the analytical run is instrument-bound and its order is fixed by the validated method.",
        "notes": "In regulated bioanalysis the quality controls decide whether a run is accepted, not the study samples -- a run where every sample looks plausible but the QCs fail is a failed run, and reporting it is a data-integrity finding rather than a scientific judgement call. Run order is part of the validated method, not a convenience: the blank placed immediately after the highest calibration standard exists specifically to measure carryover, and moving it invalidates that measurement. Protein precipitation is the fastest extraction and the least clean; if matrix effects fail the six-lot evaluation, move to solid-phase extraction rather than adjusting the acceptance criteria. Record freeze-thaw counts per sample: stability was validated for a specific number of cycles and exceeding it silently invalidates the result.",
        "autonomy_level": 2,
        "autonomy_level_reason": "Robot performs the full extraction and plate build unattended; analyst reviews integration, internal standard response and carryover before the run is accepted.",
        "automate_96_steps": ["Internal standard dispense", "Acetonitrile precipitation", "Mobile phase dilution"],
        "automate_96_head": "96-channel head",
        "automate_96_head_note": "Reagent additions are full-plate 96-head dispenses; sample transfers and the supernatant transfer use the 8-channel head with height-controlled aspiration above the pellet.",
        "automate_96_head_change": True,
        "instrument_assignment": {
            "rail_robot": ["A1", "D1", "D2", "F1", "G1"],
            "automate_96": ["C1", "C2", "C3", "E1"],
            "analyst": [],
        },
        "protocol_steps_v3": [
            {"step_number": 1, "step_type": "thaw", "instrument": "cooled_block", "description": "Thaw samples, calibrators and QCs at 4 C; log freeze-thaw counts.", "parameters": {"temperature_C": 4}, "duration_seconds": 1800},
            {"step_number": 2, "step_type": "centrifuge", "instrument": "plate_centrifuge", "description": "Vortex 10 s then spin 3000 x g, 5 min, 4 C.", "parameters": {"rcf": 3000, "duration_seconds": 300, "temperature_C": 4}, "duration_seconds": 300},
            {"step_number": 3, "step_type": "dispense", "instrument": "liquid_handler", "description": "Add 20 uL internal standard to all wells except double blanks.", "parameters": {"volume_uL": 20.0}, "duration_seconds": 120},
            {"step_number": 4, "step_type": "transfer", "instrument": "liquid_handler", "description": "Transfer 50 uL of each calibrator, QC, sample and blank, fresh tips each.", "parameters": {"volume_uL": 50.0}, "duration_seconds": 600},
            {"step_number": 5, "step_type": "dispense", "instrument": "liquid_handler", "description": "Add 150 uL cold acetonitrile against the well wall.", "parameters": {"volume_uL": 150.0, "dispense_mode": "wall", "temperature_C": 4}, "duration_seconds": 150},
            {"step_number": 6, "step_type": "mix", "instrument": "plate_shaker", "description": "Seal and shake 1000 rpm for 5 min.", "parameters": {"rpm": 1000, "duration_seconds": 300}, "duration_seconds": 300},
            {"step_number": 7, "step_type": "centrifuge", "instrument": "plate_centrifuge", "description": "Spin 4000 x g, 10 min, 4 C to pellet protein.", "parameters": {"rcf": 4000, "duration_seconds": 600, "temperature_C": 4}, "duration_seconds": 600},
            {"step_number": 8, "step_type": "transfer", "instrument": "liquid_handler", "description": "Transfer 100 uL supernatant at fixed height above the pellet.", "parameters": {"volume_uL": 100.0, "aspirate_mode": "fixed_height"}, "duration_seconds": 420},
            {"step_number": 9, "step_type": "dispense", "instrument": "liquid_handler", "description": "Dilute with 100 uL aqueous mobile phase and mix 5x.", "parameters": {"volume_uL": 100.0, "mix_cycles": 5}, "duration_seconds": 180},
            {"step_number": 10, "step_type": "seal", "instrument": "plate_sealer", "description": "Seal injection plate with pierceable mat.", "parameters": {"seal_type": "pierceable_mat"}, "duration_seconds": 45},
            {"step_number": 11, "step_type": "inject", "instrument": "lcmsms", "description": "Run validated injection order with carryover blank after the highest standard.", "parameters": {"autosampler_temperature_C": 8, "order": "suitability_blanks_standards_qcs_samples"}, "duration_seconds": 14400},
            {"step_number": 12, "step_type": "analyst_review", "instrument": "analyst", "description": "Review integration, IS response and carryover blank.", "parameters": {}, "duration_seconds": 1800},
            {"step_number": 13, "step_type": "export", "instrument": "software", "description": "Export areas, ratios, back-calculated concentrations and regression model.", "parameters": {}, "duration_seconds": 120},
        ],
    },

    # =====================================================================
    {
        "assay_id": "UNI_006",
        "name": "Reverse-phase HPLC purity and assay with system suitability",
        "field": "Universal core methods",
        "product_types": ["Small-molecule drug substance", "Drug product", "Synthetic intermediates", "Peptides", "Raw material identity and purity"],
        "purpose": "Determine the purity and content of a compound by reverse-phase separation with UV detection, gated by a system suitability test that proves the chromatographic system is fit before any sample result is accepted.",
        "robot_steps": [
            "Prepare mobile phases at deck position C1 and C2, degas both, and prime the pump with 10 column volumes -- log mobile phase preparation date and lot numbers of all solvents and modifiers.",
            "Equilibrate the column at position H1 with starting mobile phase composition until the baseline is flat and back-pressure is stable over 10 minutes.",
            "Prepare the system suitability solution at position B1: reference standard at nominal assay concentration spiked with the specified resolution marker impurity.",
            "Prepare calibration standards at position B2 by serial dilution of the reference standard across the validated range.",
            "Weigh and dissolve samples at position A1; sonicate for 10 minutes to ensure complete dissolution, then filter each through a 0.45 um syringe filter into an HPLC vial at position B3.",
            "Discard the first 0.5 mL of each filtrate -- the filter membrane adsorbs analyte until saturated and an unflushed filter biases the first millilitre low.",
            "Load the vial tray into the autosampler at position G1 held at 10 C.",
            "Inject the system suitability solution six times consecutively and evaluate before any sample is injected.",
            "Robot evaluates the suitability criteria automatically; the run aborts and alerts if resolution, tailing, plate count or replicate RSD fails -- no sample injection proceeds on an unsuitable system.",
            "Inject blanks, calibration standards low to high, then samples with a bracketing standard every ten injections.",
            "[ANALYST STEP -- robot pauses and alerts]: Review integration of any peak eluting near the void volume and any unexpected peak above the reporting threshold.",
            "Calculate purity as area percent and content against the calibration curve; flag any individual impurity above the identification threshold.",
            "Export the chromatograms, peak table, suitability results and calibration statistics to the run file.",
            "Flush the column with 20 column volumes of high-organic mobile phase and log the cumulative injection count.",
        ],
        "robot_deck_layout": {
            "A1": "Sample weighing and dissolution station",
            "B1": "System suitability solution vial position",
            "B2": "Calibration standard rack",
            "B3": "Sample HPLC vial rack -- filtered",
            "C1": "Mobile phase A reservoir -- aqueous with modifier",
            "C2": "Mobile phase B reservoir -- organic",
            "D1": "Syringe filter station -- 0.45 um",
            "E1": "Tip rack -- 1000 uL tips",
            "G1": "Autosampler tray, 10 C",
            "H1": "HPLC column compartment and pump control",
        },
        "workbench_id": "WB4",
        "rail_handoff": "Vial tray handed to autosampler; robot released for the analytical sequence.",
        "instruments_needed": ["HPLC or UPLC with UV/PDA detector", "Analytical balance", "Sonicator", "Column oven"],
        "consumables": ["HPLC vials with septa caps", "0.45 um syringe filters", "1000 uL tips", "Reverse-phase C18 analytical column"],
        "reagents": ["HPLC-grade acetonitrile or methanol", "HPLC-grade water", "Buffer or acid modifier (formic acid, TFA or phosphate)", "Certified reference standard", "Specified resolution marker impurity"],
        "throughput_samples_per_run": 40,
        "throughput_notes": "40 samples per sequence at a 15-minute method including bracketing standards; sequence length is bounded by mobile phase stability rather than by autosampler capacity.",
        "robot_active_minutes": 45,
        "total_assay_duration_hours": 12,
        "sample_volume_uL": 10,
        "detection": "UV absorbance at the compound-specific lambda max (PDA 200-400 nm collected)",
        "regulatory": ["USP <621> Chromatography (system suitability methodology)", "ICH Q2(R2) (validation of analytical procedures)", "ICH Q3A/Q3B (impurity reporting thresholds)"],
        "automation_difficulty": "moderate",
        "acceptance_criteria": {
            "resolution": ">= 2.0 between the analyte peak and the nearest eluting impurity",
            "tailing_factor": "<= 2.0",
            "theoretical_plates": ">= 2000",
            "replicate_injection_rsd": "<= 2.0% RSD across 6 replicate injections",
            "capacity_factor": ">= 2.0",
            "calibration_r2": ">= 0.999 across the validated range",
            "standard_recovery": "98-102% for the bracketing standard",
            "column_pressure_stability": "Within +/-10% of the equilibrated value across the sequence",
        },
        "acceptance_criteria_structured": [
            {"key": "resolution", "criterion_type": "resolution", "scope": "run",
             "applies_to": "reference_standard", "min": 2.0, "max": None, "unit": None,
             "display": ">= 2.0",
             "source": "Method/monograph-defined default (project-defined). USP <621> defines HOW resolution is calculated and requires system suitability be established, but sets no universal numeric limit -- do not cite <621> as the source of this value",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "tailing_factor", "criterion_type": "peak_shape", "scope": "run",
             "applies_to": "reference_standard", "min": None, "max": 2.0, "unit": None,
             "display": "<= 2.0",
             "source": "Method/monograph-defined default (project-defined); calculation methodology per USP <621>",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "theoretical_plates", "criterion_type": "column_efficiency", "scope": "run",
             "applies_to": "reference_standard", "min": 2000.0, "max": None, "unit": "plates",
             "display": ">= 2000",
             "source": "Method/monograph-defined default (project-defined); calculation methodology per USP <621>",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "replicate_injection_rsd", "criterion_type": "replicate_cv", "scope": "run",
             "applies_to": "reference_standard", "min": None, "max": 2.0, "unit": "%",
             "display": "<= 2.0% RSD over 6 injections",
             "source": "Method/monograph-defined default (project-defined); calculation methodology per USP <621>",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "capacity_factor", "criterion_type": "retention_time", "scope": "run",
             "applies_to": "reference_standard", "min": 2.0, "max": None, "unit": "k'",
             "display": ">= 2.0",
             "source": "Method/monograph-defined default (project-defined) -- keeps the analyte off the void volume",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "calibration_r2", "criterion_type": "curve_r2", "scope": "plate",
             "applies_to": "standard", "min": 0.999, "max": None, "unit": None,
             "display": ">= 0.999",
             "source": "ICH Q2(R2) requires linearity be demonstrated and the correlation coefficient reported; the 0.999 threshold is a project-defined assay-method default",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "standard_recovery", "criterion_type": "recovery", "scope": "run",
             "applies_to": "reference_standard", "min": 98.0, "max": 102.0, "unit": "%",
             "display": "98-102%",
             "source": "Internal QC SOP (project-defined) bracketing standard check",
             "source_type": "project_defined", "machine_scorable": True},
            {"key": "column_pressure_stability", "criterion_type": "pressure", "scope": "run",
             "applies_to": "all", "min": 90.0, "max": 110.0, "unit": "% of equilibrated value",
             "display": "Within +/-10% of equilibrated pressure",
             "source": "Internal QC SOP (project-defined) instrument-health check",
             "source_type": "project_defined", "machine_scorable": True},
        ],
        "well_roles": {
            "sample": {"skip": True,
                       "note": "Purity and content are the RESULT, not a pass/fail range -- specification limits belong to the product monograph, not to the analytical method. The method's job is to be demonstrably fit; the sample's number is then reported against whatever specification applies."},
            "reference_standard": {"min": 98.0, "max": 102.0, "unit": "% recovery",
                                   "note": "The suitability and bracketing standard. If this drifts, every sample bracketed by it is suspect regardless of how clean the sample chromatograms look."},
            "blank": {"min": None, "max": 1.0, "unit": "% of analyte peak area",
                      "note": "INVERTED RULE. A mobile-phase blank passes by being empty. Any peak at the analyte retention time means carryover or contaminated mobile phase."},
        },
        "environment_requirement": "Standard analytical laboratory with controlled temperature; column oven required for retention-time reproducibility.",
        "platform_compatibility": "Full for sample preparation; the analytical sequence is instrument-bound.",
        "notes": "System suitability is a gate, not a report: it is evaluated BEFORE samples are injected, and a system that fails suitability produces no reportable sample data at all. Running samples first and checking suitability afterwards is a common and serious inversion. The specific limits above are method defaults rather than universal requirements -- USP <621> standardises how resolution, tailing and plate count are calculated and requires suitability be established, but the numbers themselves come from each monograph or validated method, which is why they are labelled project-defined here. Flush syringe filters before collecting: an unsaturated membrane adsorbs analyte and biases the first millilitre low, which shows up as an unexplained low assay result on the first sample of every batch. Retention time drifting later across a sequence usually means the column is fouling or the mobile phase is evaporating its organic component; drifting earlier usually means temperature control has failed.",
        "autonomy_level": 3,
        "autonomy_level_reason": "Robot evaluates system suitability automatically and aborts the sequence before any sample injection if the system is unfit -- a genuine decision made without the analyst.",
        "automate_96_steps": [],
        "automate_96_head": "not applicable",
        "automate_96_head_note": "All transfers are into HPLC vials rather than microplates; no 96-well dispensing in this method.",
        "automate_96_head_change": False,
        "instrument_assignment": {
            "rail_robot": ["A1", "B1", "B2", "B3", "D1", "G1", "H1"],
            "automate_96": ["C1", "C2", "E1"],
            "analyst": [],
        },
        "protocol_steps_v3": [
            {"step_number": 1, "step_type": "prepare", "instrument": "liquid_handler", "description": "Prepare and degas mobile phases; prime pump with 10 column volumes.", "parameters": {"column_volumes": 10}, "duration_seconds": 900},
            {"step_number": 2, "step_type": "equilibrate", "instrument": "hplc", "description": "Equilibrate column until baseline and pressure are stable for 10 min.", "parameters": {"stability_window_seconds": 600}, "duration_seconds": 1800},
            {"step_number": 3, "step_type": "prepare", "instrument": "liquid_handler", "description": "Prepare system suitability solution with resolution marker.", "parameters": {}, "duration_seconds": 420},
            {"step_number": 4, "step_type": "serial_dilution", "instrument": "liquid_handler", "description": "Prepare calibration standards across the validated range.", "parameters": {}, "duration_seconds": 600},
            {"step_number": 5, "step_type": "dissolve", "instrument": "sonicator", "description": "Weigh, dissolve and sonicate samples for 10 min.", "parameters": {"duration_seconds": 600}, "duration_seconds": 600},
            {"step_number": 6, "step_type": "filter", "instrument": "liquid_handler", "description": "Filter through 0.45 um, discarding the first 0.5 mL.", "parameters": {"pore_size_um": 0.45, "discard_volume_mL": 0.5}, "duration_seconds": 480},
            {"step_number": 7, "step_type": "load", "instrument": "hplc", "description": "Load vial tray into autosampler at 10 C.", "parameters": {"temperature_C": 10}, "duration_seconds": 60},
            {"step_number": 8, "step_type": "system_suitability", "instrument": "hplc", "description": "Six replicate suitability injections, evaluated before any sample.", "parameters": {"injections": 6, "gate": True}, "duration_seconds": 5400},
            {"step_number": 9, "step_type": "qc_gate", "instrument": "software", "description": "Abort sequence if resolution, tailing, plates or RSD fail.", "parameters": {"abort_on_fail": True}, "duration_seconds": 30},
            {"step_number": 10, "step_type": "inject", "instrument": "hplc", "description": "Blanks, standards low to high, samples with bracketing standard every 10 injections.", "parameters": {"bracket_interval": 10}, "duration_seconds": 30000},
            {"step_number": 11, "step_type": "analyst_review", "instrument": "analyst", "description": "Review void-volume peaks and any peak above the reporting threshold.", "parameters": {}, "duration_seconds": 1800},
            {"step_number": 12, "step_type": "calculate", "instrument": "software", "description": "Area-percent purity and content against the calibration curve.", "parameters": {}, "duration_seconds": 120},
            {"step_number": 13, "step_type": "export", "instrument": "software", "description": "Export chromatograms, peak table, suitability and calibration statistics.", "parameters": {}, "duration_seconds": 120},
            {"step_number": 14, "step_type": "clean", "instrument": "hplc", "description": "Flush 20 column volumes high-organic; log cumulative injection count.", "parameters": {"column_volumes": 20}, "duration_seconds": 1800},
        ],
    },
]
